export const LAYOUT_TOGGLE_THEME = "TOGGLE_THEME"
export const LAYOUT_CHANGE_LANGUAGE = "LAYOUT_CHANGE_LANGUAGE"
export const TIMELINE_CHANGE = "TIMELINE_CHANGE"
export const REMOVE_TIMELINE = "REMOVE_TIMELINE"